### ISSUE TITLE
Stack trace in process_info module on startup

### ISSUE THREAD

**Issue by fenixnet-net** [mk23/snmpy#58]
```
2015-05-16 08:18:09.638            __init__:37  Thread-1        ERROR: 14090: [Errno 2] No such file or directory: '/proc/14090/fd'
2015-05-16 08:18:09.639            __init__:42  Thread-1        DEBUG:   Traceback (most recent call last):
2015-05-16 08:18:09.639            __init__:42  Thread-1        DEBUG:     File "/home/cameron/snmpy_test/snmpy/module/process_info.py", line 92, in update
2015-05-16 08:18:09.640            __init__:42  Thread-1        DEBUG:       p = process_data(pid)
2015-05-16 08:18:09.640            __init__:42  Thread-1        DEBUG:     File "/home/cameron/snmpy_test/snmpy/module/process_info.py", line 9, in __init__
2015-05-16 08:18:09.640            __init__:42  Thread-1        DEBUG:       self._f = len(os.listdir('/proc/%s/fd' % pid))
2015-05-16 08:18:09.640            __init__:42  Thread-1        DEBUG:   OSError: [Errno 2] No such file or directory: '/proc/14090/fd'
```

**Comment by mk23** [comment]
```
2015-05-04 11:48:07.670            __init__:37  Thread-10       ERROR: 19805: [Errno 2] No such file or directory: '/proc/19805/cmdline'
2015-05-04 11:48:07.671            __init__:42  Thread-10       DEBUG:   Traceback (most recent call last):
2015-05-04 11:48:07.672            __init__:42  Thread-10       DEBUG:     File "/home/max/dev/test_snmpy/snmpy/module/process_info.py", line 96, in update
2015-05-04 11:48:07.673            __init__:42  Thread-10       DEBUG:       p = process_data(pid)
2015-05-04 11:48:07.674            __init__:42  Thread-10       DEBUG:     File "/home/max/dev/test_snmpy/snmpy/module/process_info.py", line 9, in __init__
2015-05-04 11:48:07.675            __init__:42  Thread-10       DEBUG:       self._c = open('/proc/%s/cmdline' % pid).read().replace('\0', ' ').strip()
2015-05-04 11:48:07.675            __init__:42  Thread-10       DEBUG:   IOError: [Errno 2] No such file or directory: '/proc/19805/cmdline'
```
